version: "3.8"

services:
  redis-tokens:
    image: redis:alpine
    container_name: redis-tokens
    ports:
      - "6379:6379"
    networks:
      - postdesk

  auth-service:
    build:
      context: ./auth
      dockerfile: Dockerfile
    container_name: auth-service
    environment:
      - PORT=5001
      - STORAGE_HOST=redis-tokens
      - STORAGE_PORT=6379
      - JWT_SECRET=secret
    depends_on:
      - redis-tokens
    ports:
      - "5001:5001"
    networks:
      - postdesk

  gateway:
    build:
      context: ./gateway
      dockerfile: Dockerfile
    container_name: gateway
    environment:
      - PORT=5000
      - AUTH_HOST=auth-service
      - AUTH_PORT=5001
    depends_on:
      - auth-service
    ports:
      - "5000:5000"
    networks:
      - postdesk

networks:
  postdesk:
