version: "3.8"

services:
  redis-tokens:
    image: redis:alpine
    container_name: redis-tokens
    ports:
      - "6379:6379"
    networks:
      - postdesk

  auth-service:
    build:
      context: ./entry/auth
      dockerfile: Dockerfile
    container_name: auth-service
    environment:
      - PORT=5001
      - STORAGE_HOST=redis-tokens
      - STORAGE_PORT=6379
      - JWT_SECRET=secret
    depends_on:
      - redis-tokens
    ports:
      - "5001:5001"
    networks:
      - postdesk

  gateway:
    build:
      context: ./entry/gateway
      dockerfile: Dockerfile
    container_name: gateway
    environment:
      - PORT=5000
      - AUTH_HOST=auth-service
      - AUTH_PORT=5001
      - BROKER_HOST=kafka
      - BROKER_PORT=9092
    depends_on:
      - auth-service
      - kafka
    ports:
      - "5000:5000"
    networks:
      - postdesk

  zookeeper:
    container_name: zookeeper
    image: zookeeper:latest
    ports:
      - "2181:2181"
    networks:
      - postdesk

  kafka:
    container_name: kafka
    image: bitnami/kafka:latest
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    networks:
      - postdesk
  
  posts-loadbalancer:
    container_name: posts-loadbalancer
    build:
      context: ./posts-service/LoadBalancer
      dockerfile: Dockerfile
    image: posts-loadbalancer:latest
    ports:
      - "5003:80"
    networks:
      - postdesk
    depends_on:
      - kafka
      - posts-database
  
  post-service1:
    container_name: post-service1
    build:
      context: ./posts-service/PostService
      dockerfile: Dockerfile
    image: postservice:latest
    ports:
      - "50051:8080"
    networks:
      - postdesk
    depends_on:
      - posts-database
  
  post-service2:
    container_name: post-service2
    build:
      context: ./posts-service/PostService
      dockerfile: Dockerfile
    image: postservice:latest
    ports:
      - "50052:8080"
    networks:
      - postdesk
    depends_on:
      - posts-database

  posts-database:
    container_name: posts-database
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: "LZpb8R9Ozsrab6Vaez6L2oNsP1z79o2v"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    networks:
      - postdesk

networks:
  postdesk:
