version: "3.8"

services:
  redis-tokens:
    image: redis:alpine
    container_name: redis-tokens
    ports:
      - "6379:6379"
    networks:
      - postdesk

  auth-service:
    build:
      context: ./entry/auth
      dockerfile: Dockerfile
    container_name: auth-service
    environment:
      - PORT=5001
      - STORAGE_HOST=redis-tokens
      - STORAGE_PORT=6379
      - JWT_SECRET=secret
    depends_on:
      - redis-tokens
    ports:
      - "5001:5001"
    networks:
      - postdesk

  gateway:
    build:
      context: ./entry/gateway
      dockerfile: Dockerfile
    container_name: gateway
    environment:
      - PORT=5000
      - AUTH_HOST=auth-service
      - AUTH_PORT=5001
      - BROKER_HOST=kafka
      - BROKER_PORT=9092
    depends_on:
      - auth-service
      - kafka
    ports:
      - "5000:5000"
    networks:
      - postdesk

  zookeeper:
    container_name: zookeeper
    image: zookeeper:latest
    ports:
      - "2181:2181"
    networks:
      - postdesk
    logging:
      driver: none

  kafka:
    container_name: kafka
    image: bitnami/kafka:latest
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    networks:
      - postdesk
    logging:
      driver: none

  users_storage:
    container_name: users_storage
    image: postgres:17beta2-alpine3.20
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
    networks:
      - postdesk

  users_balancer:
    build:
      context: ./users-service/loadbalancer
      dockerfile: Dockerfile
    container_name: users_balancer
    depends_on:
      - kafka
      - users_service
    networks:
      - postdesk
    environment:
      - BROKER_HOST=kafka
      - BROKER_PORT=9092
      - SERVICES_ADDRS=users_service:5002

  users_service:
    build:
      context: ./users-service/service
      dockerfile: Dockerfile
    container_name: users_service
    environment:
      - DB_ADDR=postgres://postgres:secret@users_storage?sslmode=disable
      - PORT=5002
    depends_on:
      - users_storage
    ports:
      - "5002:5002"
    networks:
      - postdesk

networks:
  postdesk:
