name: CI Pipeline

on:
  push:
    branches-ignore: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v3

      - name: Set up Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose

      - name: Start services
        run: docker-compose -f docker-compose-entry.yaml up -d

      - name: Wait for services to start
        run: sleep 20

      - name: Run E2E tests
        run: go test -v ./... > test-results.txt
        working-directory: ./tester
        continue-on-error: false

      - name: Stop services
        run: docker-compose -f docker-compose-entry.yaml down

      - name: Report E2E results
        if: always()
        run: |
          echo "E2E Test Summary:"
          cat ./tester/test-results.txt

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Super-Linter
        uses: super-linter/super-linter@v6.7.0
        env:
          VALIDATE_ALL_CODEBASE: false
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_GO: false
          VALIDATE_GO_MODULES: false
          IGNORE_GENERATED_FILES: true
        continue-on-error: true
